### ISSUE TITLE
Documentation request: Comparisons to cobrapy, COBRA.jl, RAVEN etc

### ISSUE THREAD

**Issue by oxinabox** [COBREXA/COBREXA.jl#58]
## Target functionality

It would be good to include a section in the documentation on noteworthy differences, and pros and cons vs other FBA software.
Such as cobrapy, RAVEN and COBRA.jl

I am currently looking into what software to use for our project and I don't really know. (Other engineer i am working with is pushing for cobrapy)

## Desired output

A page in the documentation with a list of dot-points and or a table summarizing.

**Comment by exaexa** [comment]
We wanted to do this but all comparisons are super subjective.  Stuff like "feature matrix" is certainly a problematic discussion topic :D :D So we're just going to point to the relevant section in the paper when it's out.

I guess I can add 2 bullet points with the actually new things here to the readme, will do asap.

I'll leave this open here so that I don't forget to add citation.
